<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_zQB3MHCkEeyFLZsHFOyECQ" name="IAProcessModel" author="mcm" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_zQB3MXCkEeyFLZsHFOyECQ" name="InvertedAuction">
      <elements xmi:type="process:Lane" xmi:id="_zQB3MnCkEeyFLZsHFOyECQ" name="Client" actor="_mHvx4HEeEeyFLZsHFOyECQ">
        <elements xmi:type="process:Task" xmi:id="_zQB3N3CkEeyFLZsHFOyECQ" name="Submit Purchase Request" outgoing="_mconwHClEeyFLZsHFOyECQ" incoming="_lLzeIHEKEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zQB3OHCkEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zQB3OXCkEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zQB3OnCkEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zQB3O3CkEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zQB3PHCkEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zQB3PXCkEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zQB3PnCkEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zQB3P3CkEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_zQB3QHCkEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_zQB3QXCkEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_zQB3QnCkEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_zQB3Q3CkEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_56mKYHCnEeyFLZsHFOyECQ" name="End1" incoming="_56xJgHCnEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_56nYgHCnEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_56mxcHCnEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_56nYgXCnEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_8A_ZsHCoEeyFLZsHFOyECQ" name="Lesser Company Found" outgoing="_HwyosHCpEeyFLZsHFOyECQ" incoming="_8BFgUHCoEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8BAAwXCoEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8BAAwHCoEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8BAAwnCoEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8BAAw3CoEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8BAAxHCoEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8BAAxXCoEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8BAAx3CoEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8BAAxnCoEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IJjuAHCpEeyFLZsHFOyECQ" name="Gateway2" outgoing="_zPstwHCpEeyFLZsHFOyECQ _RWjncHEJEeyFLZsHFOyECQ" incoming="_HwyosHCpEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HwuXQXCpEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HwuXQHCpEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HwuXQnCpEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_zPmAEHCpEeyFLZsHFOyECQ" name="End2" incoming="_zPstwHCpEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zPmnIXCpEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zPmnIHCpEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zPmnInCpEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_QSAQQHCzEeyFLZsHFOyECQ" name="Gateway5" outgoing="_VQV8cHEJEeyFLZsHFOyECQ _eimyAHEJEeyFLZsHFOyECQ _56NcUHEJEeyFLZsHFOyECQ" incoming="_QGdHkHCzEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QGYPEnCzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QGYPEXCzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QGYPE3CzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_eifdQHEJEeyFLZsHFOyECQ" name="End4" incoming="_eimyAHEJEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eigEUXEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eigEUHEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eigEUnEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_dS_u0HEKEeyFLZsHFOyECQ" name="Start of Process" outgoing="_lLzeIHEKEeyFLZsHFOyECQ" incoming="_k7GvsHEKEeyFLZsHFOyECQ _RhIGcHEOEeyFLZsHFOyECQ">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_1Aiv8HEPEeyFLZsHFOyECQ" source="_yeJrsHEPEeyFLZsHFOyECQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dTA88HEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dTAV4HEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dTA88XEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_kDM3UHEKEeyFLZsHFOyECQ" name="Start1" outgoing="_k7GvsHEKEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDNeYXEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDNeYHEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDNeYnEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_QeD8YHENEeyFLZsHFOyECQ" name="Gateway8" outgoing="_wFNlwHEMEeyFLZsHFOyECQ _QG0hEHENEeyFLZsHFOyECQ _N_OF8HEOEeyFLZsHFOyECQ" incoming="_SdAcsHEKEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Sc8LQXEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Sc8LQHEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Sc8LQnEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_A2pGIHEOEeyFLZsHFOyECQ" name="End5" incoming="_A2vz0HEOEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A2ptMXEOEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A2ptMHEOEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A2ptMnEOEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_GWbIkHEOEeyFLZsHFOyECQ" name="Gateway13" outgoing="_RhIGcHEOEeyFLZsHFOyECQ" incoming="_N_OF8HEOEeyFLZsHFOyECQ _X46H4HEOEeyFLZsHFOyECQ">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_wb3UwHEYEeyFLZsHFOyECQ" source="_oDnQYHEYEeyFLZsHFOyECQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GWbvoHEOEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GWbIkXEOEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GWbvoXEOEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_jKnFoHEOEeyFLZsHFOyECQ" name="Gateway10" outgoing="_THUdoHENEeyFLZsHFOyECQ _vyZiAHENEeyFLZsHFOyECQ _A2vz0HEOEeyFLZsHFOyECQ _X46H4HEOEeyFLZsHFOyECQ" incoming="_JGiVMHENEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JGdcsXENEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JGdcsHENEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JGdcsnENEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_yeJrsHEPEeyFLZsHFOyECQ" text="Merging Start and Repeat Overall Procedure"/>
        <elements xmi:type="process:XORGateway" xmi:id="_6sLAkHEQEeyFLZsHFOyECQ" name="Gateway12" outgoing="_vMGXAHENEeyFLZsHFOyECQ" incoming="_kmPLkHENEeyFLZsHFOyECQ _vyZiAHENEeyFLZsHFOyECQ">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_gfmFUHEYEeyFLZsHFOyECQ" source="_Zkab4HEYEeyFLZsHFOyECQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kmK6IXENEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kmK6IHENEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kmK6InENEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_INVfgHEREeyFLZsHFOyECQ" name="Select Company" outgoing="_SdAcsHEKEeyFLZsHFOyECQ" incoming="_vMGXAHENEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GVR14XEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GVR14HEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GVR14nEKEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GVR143EKEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GVSc8HEKEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GVSc8XEKEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GVSc83EKEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GVSc8nEKEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_INXUtXEREeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_INXUtnEREeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_INXUtHEREeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_INXUt3EREeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_hzdWYHEXEeyFLZsHFOyECQ" name="Less Bids Recieved" outgoing="_QGdHkHCzEeyFLZsHFOyECQ" incoming="_MRBHEHCzEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MQ8OknCzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MQ8OkXCzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MQ8Ok3CzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_MQ8OlHCzEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_MQ8OlXCzEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_MQ8OlnCzEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_MQ8OmHCzEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_MQ8Ol3CzEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_hzfLkHEXEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_hzfLkXEXEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_hzekh3EXEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_hzfLknEXEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_Zkab4HEYEeyFLZsHFOyECQ" text="Merging ( Select another Company, Display List of Companies)"/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_oDnQYHEYEeyFLZsHFOyECQ" text="Mergin two Repeat Overall Procedure"/>
        <elements xmi:type="process:Task" xmi:id="_y1h60HEYEeyFLZsHFOyECQ" name="Submit Clarification Form" outgoing="_0wSNwHEMEeyFLZsHFOyECQ" incoming="_wFNlwHEMEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wFItQXEMEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wFItQHEMEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wFItQnEMEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wFItQ3EMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wFItRHEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wFItRXEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wFItR3EMEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wFItRnEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_y1jwAXEYEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_y1jwAnEYEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_y1jwAHEYEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_y1jwA3EYEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_-kbx8HEYEeyFLZsHFOyECQ" name="Check Clarification" outgoing="_JGiVMHENEeyFLZsHFOyECQ" incoming="_7rivsHEMEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7rd3MXEMEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7rd3MHEMEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7rd3MnEMEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7rd3M3EMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7rd3NHEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7rd3NXEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7rd3N3EMEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7rd3NnEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_-keOMHEYEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_-keOMXEYEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_-kdnJXEYEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_-keOMnEYEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_UNpWEHEZEeyFLZsHFOyECQ" name="Confirm Execution &amp; Evaluate COmpany" outgoing="_ryg6IHEPEeyFLZsHFOyECQ" incoming="_cO9ssHEPEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cO40MXEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cO40MHEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cO40MnEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_cO40M3EPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_cO40NHEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_cO40NXEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_cO40N3EPEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_cO40NnEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_UNqkN3EZEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_UNqkOHEZEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_UNqkNnEZEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_UNrLQHEZEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ZvP9cHEZEeyFLZsHFOyECQ" name="No Company Found" outgoing="_56xJgHCnEeyFLZsHFOyECQ" incoming="_KJOAAHCmEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KJHSUnCmEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KJHSUXCmEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KJHSU3CmEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KJHSVHCmEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KJHSVXCmEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KJH5YHCmEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KJH5YnCmEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KJH5YXCmEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ZvSZsnEZEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_ZvSZs3EZEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ZvSZsXEZEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ZvSZtHEZEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_62NlcHCkEeyFLZsHFOyECQ" name="System">
        <elements xmi:type="process:XORGateway" xmi:id="_3JRkMHClEeyFLZsHFOyECQ" name="Gateway1" outgoing="__jqWkHClEeyFLZsHFOyECQ _70UsIHCnEeyFLZsHFOyECQ _HynDEHCoEeyFLZsHFOyECQ" incoming="_2sLYgHClEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2sF48nClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2sF48XClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2sF483ClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ESlQ4HCzEeyFLZsHFOyECQ" name="Gateway4" outgoing="_GWaJ0HCzEeyFLZsHFOyECQ _ykAq0HEJEeyFLZsHFOyECQ" incoming="_EFugoHCzEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EFpoInCzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EFpoIXCzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EFpoI3CzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_QgosEHEJEeyFLZsHFOyECQ" name="Gateway6" outgoing="_SdIN8HEJEeyFLZsHFOyECQ" incoming="_RWjncHEJEeyFLZsHFOyECQ _VQV8cHEJEeyFLZsHFOyECQ _HynDEHCoEeyFLZsHFOyECQ">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_1YvioHEREeyFLZsHFOyECQ" source="_uLpp0HEREeyFLZsHFOyECQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QgpTIXEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QgpTIHEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QgpTInEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_y0pH0HEJEeyFLZsHFOyECQ" name="Gateway7" outgoing="_81m2cHEJEeyFLZsHFOyECQ" incoming="_ykAq0HEJEeyFLZsHFOyECQ _56NcUHEJEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yj7yUnEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yj7yUXEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yj7yU3EJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Q1_UMHENEeyFLZsHFOyECQ" name="Gateway11" outgoing="_s2ysgHENEeyFLZsHFOyECQ" incoming="_QG0hEHENEeyFLZsHFOyECQ _THUdoHENEeyFLZsHFOyECQ">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_5sz7sHEYEeyFLZsHFOyECQ" source="_0tds0HEYEeyFLZsHFOyECQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QGwPonENEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QGwPoXENEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QGwPo3ENEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_OstzMHEQEeyFLZsHFOyECQ" name="Check Categories" outgoing="_r7kVoHClEeyFLZsHFOyECQ" incoming="_mconwHClEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mcXiAXClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mcXiAHClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mcXiAnClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mcXiA3ClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mcXiBHClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mcXiBXClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mcXiB3ClEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mcXiBnClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_PUPtQHEQEeyFLZsHFOyECQ" name="Form list of companies" outgoing="_2sLYgHClEeyFLZsHFOyECQ" incoming="_r7kVoHClEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r7dn8XClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r7dn8HClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r7dn8nClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_r7dn83ClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_r7dn9HClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_r7dn9XClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_r7dn93ClEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_r7dn9nClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_uLpp0HEREeyFLZsHFOyECQ" text="Merging ( Minimum Companies Found, Forward with less Companies, Repeat Overall procedure)"/>
        <elements xmi:type="process:ScriptTask" xmi:id="_3KUN8HEREeyFLZsHFOyECQ" name="Notify Company" outgoing="_uljOoHCwEeyFLZsHFOyECQ" incoming="_SdIN8HEJEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AQfqkXCqEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AQfqkHCqEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AQfqknCqEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AQfqk3CqEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AQfqlHCqEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_AQfqlXCqEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_AQfql3CqEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_AQfqlnCqEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_3ylu4HEREeyFLZsHFOyECQ" name="Notify Client Of Less Company" outgoing="_8BFgUHCoEeyFLZsHFOyECQ" incoming="_70UsIHCnEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_70OlgnCnEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_70OlgXCnEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_70Olg3CnEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_70OlhHCnEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_70OlhXCnEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_70OlhnCnEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_70OliHCnEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_70Olh3CnEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_V5sFUHESEeyFLZsHFOyECQ" name="Analyze Bids" outgoing="_EFugoHCzEeyFLZsHFOyECQ" incoming="_90a6oHCyEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_90WCInCyEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_90WCIXCyEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_90WCI3CyEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_90WCJHCyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_90WCJXCyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_90WCJnCyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_90WCKHCyEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_90WCJ3CyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_hCDHkHEXEeyFLZsHFOyECQ" name="Notify Client of Less Bids" outgoing="_MRBHEHCzEeyFLZsHFOyECQ" incoming="_GWaJ0HCzEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GWTcIXCzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GWTcIHCzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GWTcInCzEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GWTcI3CzEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GWTcJHCzEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GWTcJXCzEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GWTcJ3CzEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GWTcJnCzEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_WjXswHEYEeyFLZsHFOyECQ" name="Display List of Companies" outgoing="_kmPLkHENEeyFLZsHFOyECQ" incoming="_81m2cHEJEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_81gv0nEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_81gv0XEJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_81gv03EJEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_81gv1HEJEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_81gv1XEJEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_81gv1nEJEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_81hW4XEJEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_81hW4HEJEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_0tds0HEYEeyFLZsHFOyECQ" text="Merging ( Proceed withBid and Clarification Satisfied)"/>
        <elements xmi:type="process:ScriptTask" xmi:id="_8yxnEHEYEeyFLZsHFOyECQ" name="Send Confirmation To Company" outgoing="_oZ2SAHELEeyFLZsHFOyECQ" incoming="_s2ysgHENEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cMTXEXELEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cMTXEHELEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cMTXEnELEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_cMTXE3ELEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_cMTXFHELEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_cMTXFXELEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_cMTXF3ELEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_cMTXFnELEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_YUrc4HEZEeyFLZsHFOyECQ" name="Notify Client" outgoing="_KJOAAHCmEeyFLZsHFOyECQ" incoming="__jqWkHClEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__jjo4XClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__jjo4HClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__jjo4nClEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__jjo43ClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__jjo5HClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__jjo5XClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__jjo53ClEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__jjo5nClEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_eeu9EHClEeyFLZsHFOyECQ" name="Company Agent" actor="_CAIqgHEeEeyFLZsHFOyECQ">
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_tzv-QHCwEeyFLZsHFOyECQ" name="Notification Arrived" outgoing="_0Lb5EHCwEeyFLZsHFOyECQ" incoming="_uljOoHCwEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tzwlUHCwEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tzv-QXCwEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tzwlUXCwEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_5jtuQHEREeyFLZsHFOyECQ" name="00:01:00" content="60000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_1x5gkHCwEeyFLZsHFOyECQ" name="Gateway3" outgoing="_SbdskHCyEeyFLZsHFOyECQ _TjmZUHCyEeyFLZsHFOyECQ" incoming="_1flokHCwEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1fgwEXCwEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1fgwEHCwEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1fgwEnCwEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_SbWX0HCyEeyFLZsHFOyECQ" name="End3" incoming="_SbdskHCyEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SbW-4XCyEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SbW-4HCyEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SbW-4nCyEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_L3d50HEPEeyFLZsHFOyECQ" name="Deadline End" outgoing="_Zevn0HEPEeyFLZsHFOyECQ" incoming="_OWh9QHEPEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L3eg4XEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L3eg4HEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L3eg4nEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_CBK-kHEZEeyFLZsHFOyECQ" name="00:01:00" content="60000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_ae42MHEPEeyFLZsHFOyECQ" name="Get Evaluation From Client and Company" outgoing="_cO9ssHEPEeyFLZsHFOyECQ _kIQkMHEPEeyFLZsHFOyECQ" incoming="_ae9usHEPEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ae5dQHEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ae42MXEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ae5dQXEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_qFvPQHEPEeyFLZsHFOyECQ" name="Merge" outgoing="_tHskYHEPEeyFLZsHFOyECQ" incoming="_qn5hIHEPEeyFLZsHFOyECQ _ryg6IHEPEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qFv2UXEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qFv2UHEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qFv2UnEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_tHmdwHEPEeyFLZsHFOyECQ" name="End6" incoming="_tHskYHEPEeyFLZsHFOyECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tHnE0XEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tHnE0HEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tHnE0nEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__pLQoHEREeyFLZsHFOyECQ" name="Check Feasibility" outgoing="_1flokHCwEeyFLZsHFOyECQ" incoming="_0Lb5EHCwEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0LXAkXCwEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0LXAkHCwEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0LXAknCwEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0LXAk3CwEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0LXAlHCwEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0LXAlXCwEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0LXAl3CwEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0LXAlnCwEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__pNs5HEREeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="__pNs5XEREeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__pNs43EREeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__pOT8HEREeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_T18r8HESEeyFLZsHFOyECQ" name="Submit Bid" outgoing="_90a6oHCyEeyFLZsHFOyECQ" incoming="_TjmZUHCyEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Tjhg0nCyEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Tjhg0XCyEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Tjhg03CyEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Tjhg1HCyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Tjhg1XCyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Tjhg1nCyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Tjhg2HCyEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Tjhg13CyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_T1_INXESEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_T1_INnESEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_T1_INHESEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_T1_vQHESEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__pTIQHEYEeyFLZsHFOyECQ" name="Confirm Acceptance of Job" outgoing="_7tYQ0HEOEeyFLZsHFOyECQ" incoming="_oZ2SAHELEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oZxZgXELEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oZxZgHELEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oZxZgnELEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oZxZg3ELEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oZxZhHELEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oZxZhXELEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oZxZh3ELEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oZxZhnELEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__pU9dnEYEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="__pU9d3EYEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__pU9dXEYEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__pVkgHEYEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ARV_sHEZEeyFLZsHFOyECQ" name="Complete Work" outgoing="_OWh9QHEPEeyFLZsHFOyECQ" incoming="_7tYQ0HEOEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7tTYUXEOEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7tTYUHEOEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7tTYUnEOEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7tTYU3EOEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7tTYVHEOEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7tTYVXEOEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7tTYV3EOEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7tTYVnEOEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ARWmyXEZEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_ARWmynEZEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ARWmyHEZEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ARWmy3EZEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BOHxAHEZEeyFLZsHFOyECQ" name="Reply Clarification" outgoing="_7rivsHEMEeyFLZsHFOyECQ" incoming="_0wSNwHEMEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0wNVQXEMEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0wNVQHEMEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0wNVQnEMEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0wNVQ3EMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0wNVRHEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0wNVRXEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0wNVR3EMEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0wNVRnEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_BOJmMHEZEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_BOJmMXEZEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_BOI_KHEZEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_BOJmMnEZEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_E5t5AHEZEeyFLZsHFOyECQ" name="Submit Work" outgoing="_ae9usHEPEeyFLZsHFOyECQ" incoming="_Zevn0HEPEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZephMXEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZephMHEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZephMnEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZephM3EPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZephNHEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZephNXEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZeqIQXEPEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZeqIQHEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_E5vHIHEZEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_E5vHIXEZEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_E5ugGHEZEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_E5vHInEZEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_VcIicHEZEeyFLZsHFOyECQ" name="Evaluate Client" outgoing="_qn5hIHEPEeyFLZsHFOyECQ" incoming="_kIQkMHEPEeyFLZsHFOyECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kILrsnEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kILrsXEPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kILrs3EPEeyFLZsHFOyECQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kILrtHEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kILrtXEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kILrtnEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kILruHEPEeyFLZsHFOyECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kILrt3EPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_VcJJiXEZEeyFLZsHFOyECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_VcJJinEZEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_VcJJiHEZEeyFLZsHFOyECQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_VcJJi3EZEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_zQB3RHCkEeyFLZsHFOyECQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_zQB3RXCkEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_zQB3RnCkEeyFLZsHFOyECQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_zQB3R3CkEeyFLZsHFOyECQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mconwHClEeyFLZsHFOyECQ" target="_OstzMHEQEeyFLZsHFOyECQ" source="_zQB3N3CkEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mcpO0HClEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_mcpO0XClEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r7kVoHClEeyFLZsHFOyECQ" target="_PUPtQHEQEeyFLZsHFOyECQ" source="_OstzMHEQEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r7kVoXClEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_r7kVonClEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2sLYgHClEeyFLZsHFOyECQ" target="_3JRkMHClEeyFLZsHFOyECQ" source="_PUPtQHEQEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2sLYgXClEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_2sLYgnClEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__jqWkHClEeyFLZsHFOyECQ" name="No Company Found" target="_YUrc4HEZEeyFLZsHFOyECQ" source="_3JRkMHClEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__jqWkXClEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="__jqWknClEeyFLZsHFOyECQ" name="newScript()" content="false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KJOAAHCmEeyFLZsHFOyECQ" target="_ZvP9cHEZEeyFLZsHFOyECQ" source="_YUrc4HEZEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KJOAAXCmEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_KJOAAnCmEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_56xJgHCnEeyFLZsHFOyECQ" target="_56mKYHCnEeyFLZsHFOyECQ" source="_ZvP9cHEZEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_56xwkHCnEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_56xwkXCnEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_70UsIHCnEeyFLZsHFOyECQ" name="Less Company Found" target="_3ylu4HEREeyFLZsHFOyECQ" source="_3JRkMHClEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_70UsIXCnEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_70UsInCnEeyFLZsHFOyECQ" name="newScript()" content="false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HynDEHCoEeyFLZsHFOyECQ" name="Minimum Companies Found" target="_QgosEHEJEeyFLZsHFOyECQ" source="_3JRkMHClEeyFLZsHFOyECQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HynDEXCoEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HynDEnCoEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8BFgUHCoEeyFLZsHFOyECQ" target="_8A_ZsHCoEeyFLZsHFOyECQ" source="_3ylu4HEREeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8BFgUXCoEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_8BFgUnCoEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HwyosHCpEeyFLZsHFOyECQ" target="_IJjuAHCpEeyFLZsHFOyECQ" source="_8A_ZsHCoEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HwzPwHCpEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HwzPwXCpEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zPstwHCpEeyFLZsHFOyECQ" name="Not Forward" target="_zPmAEHCpEeyFLZsHFOyECQ" source="_IJjuAHCpEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zPstwXCpEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_zPtU0HCpEeyFLZsHFOyECQ" name="newScript()" content="newScript()" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uljOoHCwEeyFLZsHFOyECQ" target="_tzv-QHCwEeyFLZsHFOyECQ" source="_3KUN8HEREeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uljOoXCwEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_uljOonCwEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0Lb5EHCwEeyFLZsHFOyECQ" target="__pLQoHEREeyFLZsHFOyECQ" source="_tzv-QHCwEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0Lb5EXCwEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0Lb5EnCwEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1flokHCwEeyFLZsHFOyECQ" target="_1x5gkHCwEeyFLZsHFOyECQ" source="__pLQoHEREeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1flokXCwEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_1floknCwEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SbdskHCyEeyFLZsHFOyECQ" name="Reject" target="_SbWX0HCyEeyFLZsHFOyECQ" source="_1x5gkHCwEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SbdskXCyEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SbeToHCyEeyFLZsHFOyECQ" name="newScript()" content="false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TjmZUHCyEeyFLZsHFOyECQ" name="Accept" target="_T18r8HESEeyFLZsHFOyECQ" source="_1x5gkHCwEeyFLZsHFOyECQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TjnAYHCyEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_TjnAYXCyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_90a6oHCyEeyFLZsHFOyECQ" target="_V5sFUHESEeyFLZsHFOyECQ" source="_T18r8HESEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_90bhsHCyEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_90bhsXCyEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EFugoHCzEeyFLZsHFOyECQ" target="_ESlQ4HCzEeyFLZsHFOyECQ" source="_V5sFUHESEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EFvHsHCzEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_EFvHsXCzEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GWaJ0HCzEeyFLZsHFOyECQ" name="Less Bids" target="_hCDHkHEXEeyFLZsHFOyECQ" source="_ESlQ4HCzEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GWaJ0XCzEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_GWaJ0nCzEeyFLZsHFOyECQ" name="newScript()" content="false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MRBHEHCzEeyFLZsHFOyECQ" target="_hzdWYHEXEeyFLZsHFOyECQ" source="_hCDHkHEXEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MRBHEXCzEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_MRBuIHCzEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QGdHkHCzEeyFLZsHFOyECQ" target="_QSAQQHCzEeyFLZsHFOyECQ" source="_hzdWYHEXEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QGdHkXCzEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_QGdHknCzEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RWjncHEJEeyFLZsHFOyECQ" name="Forward with less" target="_QgosEHEJEeyFLZsHFOyECQ" source="_IJjuAHCpEeyFLZsHFOyECQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RWjncXEJEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_RWkOgHEJEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SdIN8HEJEeyFLZsHFOyECQ" target="_3KUN8HEREeyFLZsHFOyECQ" source="_QgosEHEJEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SdI1AHEJEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SdI1AXEJEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VQV8cHEJEeyFLZsHFOyECQ" name="Extend Deadline" target="_QgosEHEJEeyFLZsHFOyECQ" source="_QSAQQHCzEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VQV8cXEJEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_VQV8cnEJEeyFLZsHFOyECQ" name="newScript()" content="false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eimyAHEJEeyFLZsHFOyECQ" name="No Bids Recieved" target="_eifdQHEJEeyFLZsHFOyECQ" source="_QSAQQHCzEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eimyAXEJEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_eimyAnEJEeyFLZsHFOyECQ" name="newScript()" content="false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ykAq0HEJEeyFLZsHFOyECQ" name="Minimum Bids Applied" target="_y0pH0HEJEeyFLZsHFOyECQ" source="_ESlQ4HCzEeyFLZsHFOyECQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ykAq0XEJEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ykAq0nEJEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_56NcUHEJEeyFLZsHFOyECQ" name="Proceed with less" target="_y0pH0HEJEeyFLZsHFOyECQ" source="_QSAQQHCzEeyFLZsHFOyECQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_56NcUXEJEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_56NcUnEJEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_81m2cHEJEeyFLZsHFOyECQ" target="_WjXswHEYEeyFLZsHFOyECQ" source="_y0pH0HEJEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_81m2cXEJEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_81m2cnEJEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SdAcsHEKEeyFLZsHFOyECQ" target="_QeD8YHENEeyFLZsHFOyECQ" source="_INVfgHEREeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SdAcsXEKEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SdAcsnEKEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_k7GvsHEKEeyFLZsHFOyECQ" target="_dS_u0HEKEeyFLZsHFOyECQ" source="_kDM3UHEKEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_k7GvsXEKEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_k7GvsnEKEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lLzeIHEKEeyFLZsHFOyECQ" target="_zQB3N3CkEeyFLZsHFOyECQ" source="_dS_u0HEKEeyFLZsHFOyECQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lL0FMHEKEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_lL0FMXEKEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oZ2SAHELEeyFLZsHFOyECQ" target="__pTIQHEYEeyFLZsHFOyECQ" source="_8yxnEHEYEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oZ2SAXELEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oZ2SAnELEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wFNlwHEMEeyFLZsHFOyECQ" name="Proceed with Contractor" target="_y1h60HEYEeyFLZsHFOyECQ" source="_QeD8YHENEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wFNlwXEMEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_wFNlwnEMEeyFLZsHFOyECQ" name="newScript()" content="newScript()" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0wSNwHEMEeyFLZsHFOyECQ" target="_BOHxAHEZEeyFLZsHFOyECQ" source="_y1h60HEYEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0wSNwXEMEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0wSNwnEMEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7rivsHEMEeyFLZsHFOyECQ" target="_-kbx8HEYEeyFLZsHFOyECQ" source="_BOHxAHEZEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7rjWwHEMEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7rjWwXEMEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JGiVMHENEeyFLZsHFOyECQ" target="_jKnFoHEOEeyFLZsHFOyECQ" source="_-kbx8HEYEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JGiVMXENEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_JGiVMnENEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QG0hEHENEeyFLZsHFOyECQ" name="Proceed with bid" target="_Q1_UMHENEeyFLZsHFOyECQ" source="_QeD8YHENEeyFLZsHFOyECQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QG0hEXENEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_QG0hEnENEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_THUdoHENEeyFLZsHFOyECQ" name="Satisfied" target="_Q1_UMHENEeyFLZsHFOyECQ" source="_jKnFoHEOEeyFLZsHFOyECQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_THUdoXENEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_THUdonENEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kmPLkHENEeyFLZsHFOyECQ" target="_6sLAkHEQEeyFLZsHFOyECQ" source="_WjXswHEYEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kmPyoHENEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kmPyoXENEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s2ysgHENEeyFLZsHFOyECQ" target="_8yxnEHEYEeyFLZsHFOyECQ" source="_Q1_UMHENEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s2zTkHENEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s2zTkXENEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vMGXAHENEeyFLZsHFOyECQ" target="_INVfgHEREeyFLZsHFOyECQ" source="_6sLAkHEQEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vMGXAXENEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_vMG-EHENEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vyZiAHENEeyFLZsHFOyECQ" name="Select another Company" target="_6sLAkHEQEeyFLZsHFOyECQ" source="_jKnFoHEOEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vyaJEHENEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_vyaJEXENEeyFLZsHFOyECQ" name="newScript()" content="newScript()" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A2vz0HEOEeyFLZsHFOyECQ" name="Withdraw Request" target="_A2pGIHEOEeyFLZsHFOyECQ" source="_jKnFoHEOEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A2vz0XEOEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_A2vz0nEOEeyFLZsHFOyECQ" name="newScript()" content="newScript()" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_N_OF8HEOEeyFLZsHFOyECQ" name="Repeat Overall Procedure" target="_GWbIkHEOEeyFLZsHFOyECQ" source="_QeD8YHENEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_N_OF8XEOEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_N_OF8nEOEeyFLZsHFOyECQ" name="newScript()" content="newScript()" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RhIGcHEOEeyFLZsHFOyECQ" target="_dS_u0HEKEeyFLZsHFOyECQ" source="_GWbIkHEOEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RhIGcXEOEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_RhIGcnEOEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_X46H4HEOEeyFLZsHFOyECQ" name="Repeat Overall Procedure" target="_GWbIkHEOEeyFLZsHFOyECQ" source="_jKnFoHEOEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_X46u8HEOEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_X46u8XEOEeyFLZsHFOyECQ" name="newScript()" content="newScript()" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7tYQ0HEOEeyFLZsHFOyECQ" target="_ARV_sHEZEeyFLZsHFOyECQ" source="__pTIQHEYEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7tYQ0XEOEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7tYQ0nEOEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OWh9QHEPEeyFLZsHFOyECQ" target="_L3d50HEPEeyFLZsHFOyECQ" source="_ARV_sHEZEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OWh9QXEPEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_OWh9QnEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Zevn0HEPEeyFLZsHFOyECQ" target="_E5t5AHEZEeyFLZsHFOyECQ" source="_L3d50HEPEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Zevn0XEPEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Zevn0nEPEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ae9usHEPEeyFLZsHFOyECQ" target="_ae42MHEPEeyFLZsHFOyECQ" source="_E5t5AHEZEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ae9usXEPEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ae9usnEPEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cO9ssHEPEeyFLZsHFOyECQ" target="_UNpWEHEZEeyFLZsHFOyECQ" source="_ae42MHEPEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cO9ssXEPEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_cO9ssnEPEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kIQkMHEPEeyFLZsHFOyECQ" target="_VcIicHEZEeyFLZsHFOyECQ" source="_ae42MHEPEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kIQkMXEPEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kIQkMnEPEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qn5hIHEPEeyFLZsHFOyECQ" target="_qFvPQHEPEeyFLZsHFOyECQ" source="_VcIicHEZEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qn5hIXEPEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_qn5hInEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ryg6IHEPEeyFLZsHFOyECQ" target="_qFvPQHEPEeyFLZsHFOyECQ" source="_UNpWEHEZEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ryg6IXEPEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ryg6InEPEeyFLZsHFOyECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tHskYHEPEeyFLZsHFOyECQ" target="_tHmdwHEPEeyFLZsHFOyECQ" source="_qFvPQHEPEeyFLZsHFOyECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tHskYXEPEeyFLZsHFOyECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_tHskYnEPEeyFLZsHFOyECQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_CAIqgHEeEeyFLZsHFOyECQ" name="Agent"/>
      <actors xmi:type="process:Actor" xmi:id="_mHvx4HEeEeyFLZsHFOyECQ" name="Client" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_zQB3THCkEeyFLZsHFOyECQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_zQB3TXCkEeyFLZsHFOyECQ">
        <name xmi:type="expression:Expression" xmi:id="_zQB3TnCkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_zQB3T3CkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_zQB3UHCkEeyFLZsHFOyECQ">
        <name xmi:type="expression:Expression" xmi:id="_zQB3UXCkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_zQB3UnCkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_zQB3U3CkEeyFLZsHFOyECQ">
        <name xmi:type="expression:Expression" xmi:id="_zQB3VHCkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_zQB3VXCkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_zQB3VnCkEeyFLZsHFOyECQ">
        <name xmi:type="expression:Expression" xmi:id="_zQB3V3CkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_zQB3WHCkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_zQB3WXCkEeyFLZsHFOyECQ">
        <name xmi:type="expression:Expression" xmi:id="_zQB3WnCkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_zQB3W3CkEeyFLZsHFOyECQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_SMoQ4HVIEeylMKf7oYjKGg" name="User">
      <elements xmi:type="process:StartEvent" xmi:id="_jv9kwHVIEeylMKf7oYjKGg" name="Start2" outgoing="_kkmtwHVIEeylMKf7oYjKGg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_jv-L0XVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_jv-L0HVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_jv-L0nVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_n6o1cHVIEeylMKf7oYjKGg" name="Open Registration Page" outgoing="_PxdZgHVJEeylMKf7oYjKGg" incoming="_kkmtwHVIEeylMKf7oYjKGg" actor="_YEJBYHVJEeylMKf7oYjKGg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_kkW2IXVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_kkW2IHVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_kkW2InVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_kkW2I3VIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_kkXdMHVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kkXdMXVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_kkXdM3VIEeylMKf7oYjKGg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_kkXdMnVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_n6rRsHVIEeylMKf7oYjKGg">
          <targetForm xmi:type="expression:Expression" xmi:id="_n6rRsXVIEeylMKf7oYjKGg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_n6qqp3VIEeylMKf7oYjKGg"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_n6rRsnVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_sLmUUHVIEeylMKf7oYjKGg" name="Fill Data Fields" outgoing="_qkqLsHVIEeylMKf7oYjKGg" incoming="_QKUlcHVJEeylMKf7oYjKGg" actor="_YEJBYHVJEeylMKf7oYjKGg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_oPpcIXVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_oPpcIHVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_oPpcInVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_oPpcI3VIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_oPpcJHVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oPpcJXVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_oPpcJ3VIEeylMKf7oYjKGg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_oPpcJnVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_sLoJh3VIEeylMKf7oYjKGg">
          <targetForm xmi:type="expression:Expression" xmi:id="_sLoJiHVIEeylMKf7oYjKGg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_sLoJhnVIEeylMKf7oYjKGg"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_sLoJiXVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_uVFJUHVIEeylMKf7oYjKGg" name="Submit Registration" outgoing="_BSICIHVJEeylMKf7oYjKGg" incoming="_qkqLsHVIEeylMKf7oYjKGg" actor="_YEJBYHVJEeylMKf7oYjKGg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_qkksIXVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_qkksIHVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_qkksInVIEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_qkksI3VIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_qkksJHVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qkksJXVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_qkksJ3VIEeylMKf7oYjKGg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_qkksJnVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_uVG-iXVIEeylMKf7oYjKGg">
          <targetForm xmi:type="expression:Expression" xmi:id="_uVG-inVIEeylMKf7oYjKGg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_uVG-iHVIEeylMKf7oYjKGg"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_uVHlkHVIEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_Bq5HcHVJEeylMKf7oYjKGg" name="Gateway14" outgoing="_CVCQoHVJEeylMKf7oYjKGg _QoJw8HVJEeylMKf7oYjKGg" incoming="_BSICIHVJEeylMKf7oYjKGg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_BSCikXVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_BSCikHVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_BSCiknVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_P_EXsHVJEeylMKf7oYjKGg" name="Gateway15" outgoing="_QKUlcHVJEeylMKf7oYjKGg" incoming="_PxdZgHVJEeylMKf7oYjKGg _QoJw8HVJEeylMKf7oYjKGg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_PxZIEXVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_PxZIEHVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_PxZIEnVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_WkCgkHVJEeylMKf7oYjKGg" name="End7" incoming="_WkIAIHVJEeylMKf7oYjKGg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_WkCgknVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_WkCgkXVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_WkCgk3VJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ScriptTask" xmi:id="_XQev0HVJEeylMKf7oYjKGg" name="Register User" outgoing="_WkIAIHVJEeylMKf7oYjKGg" incoming="_CVCQoHVJEeylMKf7oYjKGg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_CU8xEXVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_CU8xEHVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_CU8xEnVJEeylMKf7oYjKGg" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_CU8xE3VJEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_CU8xFHVJEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_CU8xFXVJEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_CU8xF3VJEeylMKf7oYjKGg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_CU8xFnVJEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_SRDd4HVIEeylMKf7oYjKGg">
        <targetForm xmi:type="expression:Expression" xmi:id="_SRDd4XVIEeylMKf7oYjKGg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_SRDd4nVIEeylMKf7oYjKGg">
        <targetForm xmi:type="expression:Expression" xmi:id="_SRDd43VIEeylMKf7oYjKGg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kkmtwHVIEeylMKf7oYjKGg" target="_n6o1cHVIEeylMKf7oYjKGg" source="_jv9kwHVIEeylMKf7oYjKGg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kknU0HVIEeylMKf7oYjKGg"/>
        <condition xmi:type="expression:Expression" xmi:id="_kknU0XVIEeylMKf7oYjKGg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qkqLsHVIEeylMKf7oYjKGg" target="_uVFJUHVIEeylMKf7oYjKGg" source="_sLmUUHVIEeylMKf7oYjKGg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qkqLsXVIEeylMKf7oYjKGg"/>
        <condition xmi:type="expression:Expression" xmi:id="_qkqLsnVIEeylMKf7oYjKGg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BSICIHVJEeylMKf7oYjKGg" target="_Bq5HcHVJEeylMKf7oYjKGg" source="_uVFJUHVIEeylMKf7oYjKGg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BSICIXVJEeylMKf7oYjKGg"/>
        <condition xmi:type="expression:Expression" xmi:id="_BSICInVJEeylMKf7oYjKGg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CVCQoHVJEeylMKf7oYjKGg" name="Valid Data" target="_XQev0HVJEeylMKf7oYjKGg" source="_Bq5HcHVJEeylMKf7oYjKGg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CVCQoXVJEeylMKf7oYjKGg"/>
        <condition xmi:type="expression:Expression" xmi:id="_CVCQonVJEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PxdZgHVJEeylMKf7oYjKGg" target="_P_EXsHVJEeylMKf7oYjKGg" source="_n6o1cHVIEeylMKf7oYjKGg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PxdZgXVJEeylMKf7oYjKGg"/>
        <condition xmi:type="expression:Expression" xmi:id="_PxdZgnVJEeylMKf7oYjKGg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QKUlcHVJEeylMKf7oYjKGg" target="_sLmUUHVIEeylMKf7oYjKGg" source="_P_EXsHVJEeylMKf7oYjKGg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QKVMgHVJEeylMKf7oYjKGg"/>
        <condition xmi:type="expression:Expression" xmi:id="_QKVMgXVJEeylMKf7oYjKGg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QoJw8HVJEeylMKf7oYjKGg" name="Invalid Data" target="_P_EXsHVJEeylMKf7oYjKGg" source="_Bq5HcHVJEeylMKf7oYjKGg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QoKYAHVJEeylMKf7oYjKGg"/>
        <condition xmi:type="expression:Expression" xmi:id="_QoKYAXVJEeylMKf7oYjKGg" name="newScript()" content="newScript()" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WkIAIHVJEeylMKf7oYjKGg" target="_WkCgkHVJEeylMKf7oYjKGg" source="_XQev0HVJEeylMKf7oYjKGg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WkIAIXVJEeylMKf7oYjKGg"/>
        <condition xmi:type="expression:Expression" xmi:id="_WkIAInVJEeylMKf7oYjKGg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_YEJBYHVJEeylMKf7oYjKGg" name="User"/>
      <contract xmi:type="process:Contract" xmi:id="_SRDd5HVIEeylMKf7oYjKGg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SRC20HVIEeylMKf7oYjKGg">
        <name xmi:type="expression:Expression" xmi:id="_SRC20XVIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SRC20nVIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SRC203VIEeylMKf7oYjKGg">
        <name xmi:type="expression:Expression" xmi:id="_SRC21HVIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SRC21XVIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SRC21nVIEeylMKf7oYjKGg">
        <name xmi:type="expression:Expression" xmi:id="_SRC213VIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SRC22HVIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SRC22XVIEeylMKf7oYjKGg">
        <name xmi:type="expression:Expression" xmi:id="_SRC22nVIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SRC223VIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SRC23HVIEeylMKf7oYjKGg">
        <name xmi:type="expression:Expression" xmi:id="_SRC23XVIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SRC23nVIEeylMKf7oYjKGg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_zQB3XHCkEeyFLZsHFOyECQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_zQB3XXCkEeyFLZsHFOyECQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_zQB3XnCkEeyFLZsHFOyECQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_zQB3X3CkEeyFLZsHFOyECQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_zQB3YHCkEeyFLZsHFOyECQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_zQB3YXCkEeyFLZsHFOyECQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_zQB3YnCkEeyFLZsHFOyECQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_zQB3Y3CkEeyFLZsHFOyECQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_zQB3ZHCkEeyFLZsHFOyECQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_zQB3ZXCkEeyFLZsHFOyECQ" type="Process" element="_zQB3MHCkEeyFLZsHFOyECQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_zQB3ZnCkEeyFLZsHFOyECQ" type="2007" element="_zQB3MXCkEeyFLZsHFOyECQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_zQB3Z3CkEeyFLZsHFOyECQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_zQB3aHCkEeyFLZsHFOyECQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_zQB3aXCkEeyFLZsHFOyECQ" type="3007" element="_zQB3MnCkEeyFLZsHFOyECQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_zQB3anCkEeyFLZsHFOyECQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_zQB3a3CkEeyFLZsHFOyECQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_zQB3bHCkEeyFLZsHFOyECQ" type="3005" element="_zQB3N3CkEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zQB3bXCkEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zQB3bnCkEeyFLZsHFOyECQ" x="213" y="78" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_56omoHCnEeyFLZsHFOyECQ" type="3003" element="_56mKYHCnEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_56omonCnEeyFLZsHFOyECQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_56omo3CnEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_56omoXCnEeyFLZsHFOyECQ" x="876" y="37"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8BAn0HCoEeyFLZsHFOyECQ" type="3027" element="_8A_ZsHCoEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8BBO4HCoEeyFLZsHFOyECQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8BAn0XCoEeyFLZsHFOyECQ" x="805" y="167" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IJljMHCpEeyFLZsHFOyECQ" type="3008" element="_IJjuAHCpEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IJmKQHCpEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IJmKQXCpEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IJljMXCpEeyFLZsHFOyECQ" x="975" y="178" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zPnOMHCpEeyFLZsHFOyECQ" type="3003" element="_zPmAEHCpEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_zPnOMnCpEeyFLZsHFOyECQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_zPnOM3CpEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zPnOMXCpEeyFLZsHFOyECQ" x="1143" y="136"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QSCFcHCzEeyFLZsHFOyECQ" type="3008" element="_QSAQQHCzEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QSCsgHCzEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_QSCsgXCzEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QSCFcXCzEeyFLZsHFOyECQ" x="2343" y="78" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eigrYHEJEeyFLZsHFOyECQ" type="3003" element="_eifdQHEJEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_eigrYnEJEeyFLZsHFOyECQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_eigrY3EJEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eigrYXEJEeyFLZsHFOyECQ" x="2493" y="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dTBkAHEKEeyFLZsHFOyECQ" type="3008" element="_dS_u0HEKEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dTBkAnEKEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dTBkA3EKEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dTBkAXEKEeyFLZsHFOyECQ" x="124" y="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDOFcHEKEeyFLZsHFOyECQ" type="3002" element="_kDM3UHEKEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDOsgHEKEeyFLZsHFOyECQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kDOsgXEKEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDOFcXEKEeyFLZsHFOyECQ" x="42" y="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QeFxkHENEeyFLZsHFOyECQ" type="3008" element="_QeD8YHENEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QeGYoHENEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_QeGYoXENEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QeFxkXENEeyFLZsHFOyECQ" x="2797" y="166" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_A2qUQHEOEeyFLZsHFOyECQ" type="3003" element="_A2pGIHEOEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_A2qUQnEOEeyFLZsHFOyECQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_A2qUQ3EOEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A2qUQXEOEeyFLZsHFOyECQ" x="3557" y="175"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GWbvonEOEeyFLZsHFOyECQ" type="3008" element="_GWbIkHEOEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_GWcWsHEOEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GWcWsXEOEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GWbvo3EOEeyFLZsHFOyECQ" x="2797" y="10"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jKoTwnEOEeyFLZsHFOyECQ" type="3008" element="_jKnFoHEOEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jKo60HEOEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jKph4HEOEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jKoTw3EOEeyFLZsHFOyECQ" x="3399" y="158" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_yeKSwHEPEeyFLZsHFOyECQ" type="3015" element="_yeJrsHEPEeyFLZsHFOyECQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_yeK50HEPEeyFLZsHFOyECQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_yeKSwXEPEeyFLZsHFOyECQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_yeKSwnEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_yeKSw3EPEeyFLZsHFOyECQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yeKSxHEPEeyFLZsHFOyECQ" x="80" y="164" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6sM1wHEQEeyFLZsHFOyECQ" type="3008" element="_6sLAkHEQEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_6sNc0HEQEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6sNc0XEQEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6sM1wXEQEeyFLZsHFOyECQ" x="2533" y="167" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_INX7wHEREeyFLZsHFOyECQ" type="3005" element="_INVfgHEREeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_INYi0HEREeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_INX7wXEREeyFLZsHFOyECQ" x="2625" y="164" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hzfyoHEXEeyFLZsHFOyECQ" type="3005" element="_hzdWYHEXEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_hzgZsHEXEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hzfyoXEXEeyFLZsHFOyECQ" x="2147" y="74" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_ZkbC8HEYEeyFLZsHFOyECQ" type="3015" element="_Zkab4HEYEeyFLZsHFOyECQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZkbqAHEYEeyFLZsHFOyECQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_ZkbC8XEYEeyFLZsHFOyECQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_ZkbC8nEYEeyFLZsHFOyECQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_ZkbC83EYEeyFLZsHFOyECQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZkbC9HEYEeyFLZsHFOyECQ" x="2392" y="213" width="120" height="80"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_oDnQYXEYEeyFLZsHFOyECQ" type="3015" element="_oDnQYHEYEeyFLZsHFOyECQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_oDn3cHEYEeyFLZsHFOyECQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_oDnQYnEYEeyFLZsHFOyECQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_oDnQY3EYEeyFLZsHFOyECQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_oDnQZHEYEeyFLZsHFOyECQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oDnQZXEYEeyFLZsHFOyECQ" x="2626" y="18" width="133"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y1kXEHEYEeyFLZsHFOyECQ" type="3005" element="_y1h60HEYEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_y1k-IHEYEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y1kXEXEYEeyFLZsHFOyECQ" x="3019" y="155" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-ke1QHEYEeyFLZsHFOyECQ" type="3005" element="_-kbx8HEYEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-kfcUHEYEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-ke1QXEYEeyFLZsHFOyECQ" x="3215" y="154" width="116" height="57"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UNrLQXEZEeyFLZsHFOyECQ" type="3005" element="_UNpWEHEZEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_UNryUHEZEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UNrLQnEZEeyFLZsHFOyECQ" x="3632" y="220" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZvTAwHEZEeyFLZsHFOyECQ" type="3005" element="_ZvP9cHEZEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZvTn0HEZEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZvTAwXEZEeyFLZsHFOyECQ" x="671" y="18" width="128" height="64"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_zQB3c3CkEeyFLZsHFOyECQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_zQB3dHCkEeyFLZsHFOyECQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_zQB3dXCkEeyFLZsHFOyECQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_zQB3dnCkEeyFLZsHFOyECQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zQB3d3CkEeyFLZsHFOyECQ" x="23" y="10" width="4077" height="357"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_62PaoHCkEeyFLZsHFOyECQ" type="3007" element="_62NlcHCkEeyFLZsHFOyECQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_62QBsHCkEeyFLZsHFOyECQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_62QBsXCkEeyFLZsHFOyECQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_3JSyUHClEeyFLZsHFOyECQ" type="3008" element="_3JRkMHClEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_3JUAcHClEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_3JUAcXClEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3JSyUXClEeyFLZsHFOyECQ" x="517" y="150" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ESmfAHCzEeyFLZsHFOyECQ" type="3008" element="_ESlQ4HCzEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ESnGEHCzEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ESntIHCzEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ESmfAXCzEeyFLZsHFOyECQ" x="2032" y="179" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Qgp6MHEJEeyFLZsHFOyECQ" type="3008" element="_QgosEHEJEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Qgp6MnEJEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Qgp6M3EJEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Qgp6MXEJEeyFLZsHFOyECQ" x="1208" y="56"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y0pu4HEJEeyFLZsHFOyECQ" type="3008" element="_y0pH0HEJEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_y0pu4nEJEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_y0pu43EJEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y0pu4XEJEeyFLZsHFOyECQ" x="2344" y="178" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Q1_7Q3ENEeyFLZsHFOyECQ" type="3008" element="_Q1_UMHENEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Q1_7RXENEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Q1_7RnENEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q1_7RHENEeyFLZsHFOyECQ" x="2837" y="50" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OsvBU3EQEeyFLZsHFOyECQ" type="3028" element="_OstzMHEQEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OsvBVXEQEeyFLZsHFOyECQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OsvBVHEQEeyFLZsHFOyECQ" x="193" y="146" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PUSJgHEQEeyFLZsHFOyECQ" type="3028" element="_PUPtQHEQEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PUSwkHEQEeyFLZsHFOyECQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PUSJgXEQEeyFLZsHFOyECQ" x="345" y="141" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_uLqQ4HEREeyFLZsHFOyECQ" type="3015" element="_uLpp0HEREeyFLZsHFOyECQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_uLqQ5XEREeyFLZsHFOyECQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_uLqQ4XEREeyFLZsHFOyECQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_uLqQ4nEREeyFLZsHFOyECQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_uLqQ43EREeyFLZsHFOyECQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uLqQ5HEREeyFLZsHFOyECQ" x="1337" y="67" width="131" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3KWDIHEREeyFLZsHFOyECQ" type="3028" element="_3KUN8HEREeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3KWqMHEREeyFLZsHFOyECQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3KWDIXEREeyFLZsHFOyECQ" x="1188" y="159" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3ynkFHEREeyFLZsHFOyECQ" type="3028" element="_3ylu4HEREeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3yoLIHEREeyFLZsHFOyECQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3ynkFXEREeyFLZsHFOyECQ" x="687" y="146" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_V5uhkHESEeyFLZsHFOyECQ" type="3028" element="_V5sFUHESEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_V5vIoHESEeyFLZsHFOyECQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_V5uhkXESEeyFLZsHFOyECQ" x="1865" y="178" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hCEVs3EXEeyFLZsHFOyECQ" type="3028" element="_hCDHkHEXEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_hCE8wHEXEeyFLZsHFOyECQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hCEVtHEXEeyFLZsHFOyECQ" x="2135" y="66" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WjYT2HEYEeyFLZsHFOyECQ" type="3028" element="_WjXswHEYEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_WjY64HEYEeyFLZsHFOyECQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WjYT2XEYEeyFLZsHFOyECQ" x="2492" y="173" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_0teT4HEYEeyFLZsHFOyECQ" type="3015" element="_0tds0HEYEeyFLZsHFOyECQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_0te68HEYEeyFLZsHFOyECQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_0teT4XEYEeyFLZsHFOyECQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_0teT4nEYEeyFLZsHFOyECQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_0teT43EYEeyFLZsHFOyECQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0teT5HEYEeyFLZsHFOyECQ" x="2693" y="55" height="86"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8y0DUHEYEeyFLZsHFOyECQ" type="3028" element="_8yxnEHEYEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8y0qYHEYEeyFLZsHFOyECQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8y0DUXEYEeyFLZsHFOyECQ" x="2815" y="179" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YUt5IHEZEeyFLZsHFOyECQ" type="3028" element="_YUrc4HEZEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_YUugMHEZEeyFLZsHFOyECQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YUt5IXEZEeyFLZsHFOyECQ" x="687" y="41" width="100" height="49"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_62PaoXCkEeyFLZsHFOyECQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_62PaonCkEeyFLZsHFOyECQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_62Pao3CkEeyFLZsHFOyECQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_62QBsnCkEeyFLZsHFOyECQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_62PapHCkEeyFLZsHFOyECQ" x="48" y="304" width="1677" height="445"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_eevkIHClEeyFLZsHFOyECQ" type="3007" element="_eeu9EHClEeyFLZsHFOyECQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_eewLMHClEeyFLZsHFOyECQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eewLMXClEeyFLZsHFOyECQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_tzxMYHCwEeyFLZsHFOyECQ" type="3017" element="_tzv-QHCwEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_tzxzcHCwEeyFLZsHFOyECQ" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_tzxzcXCwEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tzxMYXCwEeyFLZsHFOyECQ" x="1220" y="143"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1x6HoHCwEeyFLZsHFOyECQ" type="3008" element="_1x5gkHCwEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1x6HonCwEeyFLZsHFOyECQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1x6Ho3CwEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1x6HoXCwEeyFLZsHFOyECQ" x="1519" y="133" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SbXl8HCyEeyFLZsHFOyECQ" type="3003" element="_SbWX0HCyEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SbYNAHCyEeyFLZsHFOyECQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SbYNAXCyEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SbXl8XCyEeyFLZsHFOyECQ" x="1709" y="53"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L3fH8HEPEeyFLZsHFOyECQ" type="3017" element="_L3d50HEPEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_L3fvAHEPEeyFLZsHFOyECQ" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_L3fvAXEPEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L3fH8XEPEeyFLZsHFOyECQ" x="3215" y="224"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ae5dQnEPEeyFLZsHFOyECQ" type="3009" element="_ae42MHEPEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ae6EUHEPEeyFLZsHFOyECQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ae6EUXEPEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ae5dQ3EPEeyFLZsHFOyECQ" x="3614" y="218"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qFwdYHEPEeyFLZsHFOyECQ" type="3009" element="_qFvPQHEPEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qFxEcHEPEeyFLZsHFOyECQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qFxEcXEPEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qFwdYXEPEeyFLZsHFOyECQ" x="3949" y="218"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tHnr4HEPEeyFLZsHFOyECQ" type="3003" element="_tHmdwHEPEeyFLZsHFOyECQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_tHoS8HEPEeyFLZsHFOyECQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_tHoS8XEPEeyFLZsHFOyECQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tHnr4XEPEeyFLZsHFOyECQ" x="4060" y="222"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__pO7AHEREeyFLZsHFOyECQ" type="3005" element="__pLQoHEREeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__pQJIHEREeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__pO7AXEREeyFLZsHFOyECQ" x="1339" y="130" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_T2A9YHESEeyFLZsHFOyECQ" type="3005" element="_T18r8HESEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_T2BkcHESEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_T2A9YXESEeyFLZsHFOyECQ" x="1664" y="218" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__pVkgXEYEeyFLZsHFOyECQ" type="3005" element="__pTIQHEYEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__pWyoHEYEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__pVkgnEYEeyFLZsHFOyECQ" x="2815" y="208" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ARXN0HEZEeyFLZsHFOyECQ" type="3005" element="_ARV_sHEZEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ARXN0nEZEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ARXN0XEZEeyFLZsHFOyECQ" x="3039" y="214" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BOJmM3EZEeyFLZsHFOyECQ" type="3005" element="_BOHxAHEZEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BOKNQHEZEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BOJmNHEZEeyFLZsHFOyECQ" x="3049" y="52" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E5vHI3EZEeyFLZsHFOyECQ" type="3005" element="_E5t5AHEZEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E5vHJXEZEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E5vHJHEZEeyFLZsHFOyECQ" x="3335" y="212" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VcJwkHEZEeyFLZsHFOyECQ" type="3005" element="_VcIicHEZEeyFLZsHFOyECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VcJwknEZEeyFLZsHFOyECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VcJwkXEZEeyFLZsHFOyECQ" x="3767" y="213" width="100" height="49"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eevkIXClEeyFLZsHFOyECQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eevkInClEeyFLZsHFOyECQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eevkI3ClEeyFLZsHFOyECQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eewLMnClEeyFLZsHFOyECQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eevkJHClEeyFLZsHFOyECQ" x="48" y="708" width="1677" height="450"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_zQB3eHCkEeyFLZsHFOyECQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_zQB3eXCkEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_zQB3enCkEeyFLZsHFOyECQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_zQB3e3CkEeyFLZsHFOyECQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zQB3fHCkEeyFLZsHFOyECQ" width="4250" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_SREsAHVIEeylMKf7oYjKGg" type="2007" element="_SMoQ4HVIEeylMKf7oYjKGg">
      <children xmi:type="notation:DecorationNode" xmi:id="_SRFTEHVIEeylMKf7oYjKGg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_SRFTEXVIEeylMKf7oYjKGg" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_jv_Z8HVIEeylMKf7oYjKGg" type="3002" element="_jv9kwHVIEeylMKf7oYjKGg" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_jwABAHVIEeylMKf7oYjKGg" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_jwABAXVIEeylMKf7oYjKGg" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jv_Z8XVIEeylMKf7oYjKGg" x="65" y="104"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_n6r4wHVIEeylMKf7oYjKGg" type="3005" element="_n6o1cHVIEeylMKf7oYjKGg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_n6sf0HVIEeylMKf7oYjKGg" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_n6r4wXVIEeylMKf7oYjKGg" x="172" y="94" width="125" height="62"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_sLowkHVIEeylMKf7oYjKGg" type="3005" element="_sLmUUHVIEeylMKf7oYjKGg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_sLpXoHVIEeylMKf7oYjKGg" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sLowkXVIEeylMKf7oYjKGg" x="439" y="94" width="100" height="49"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_uVHlkXVIEeylMKf7oYjKGg" type="3005" element="_uVFJUHVIEeylMKf7oYjKGg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_uVIMoHVIEeylMKf7oYjKGg" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uVHlknVIEeylMKf7oYjKGg" x="594" y="94" width="100" height="49"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Bq68oHVJEeylMKf7oYjKGg" type="3008" element="_Bq5HcHVJEeylMKf7oYjKGg" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_Bq7jsHVJEeylMKf7oYjKGg" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Bq7jsXVJEeylMKf7oYjKGg" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Bq68oXVJEeylMKf7oYjKGg" x="760" y="97" width="42" height="42"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_P_HbAHVJEeylMKf7oYjKGg" type="3008" element="_P_EXsHVJEeylMKf7oYjKGg" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_P_ICEHVJEeylMKf7oYjKGg" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_P_IpIHVJEeylMKf7oYjKGg" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P_HbAXVJEeylMKf7oYjKGg" x="344" y="95" width="42" height="42"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_WkDHoHVJEeylMKf7oYjKGg" type="3003" element="_WkCgkHVJEeylMKf7oYjKGg" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_WkDusHVJEeylMKf7oYjKGg" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_WkDusXVJEeylMKf7oYjKGg" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WkDHoXVJEeylMKf7oYjKGg" x="1088" y="168"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_XQhzIHVJEeylMKf7oYjKGg" type="3028" element="_XQev0HVJEeylMKf7oYjKGg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_XQiaMHVJEeylMKf7oYjKGg" type="5018"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XQhzIXVJEeylMKf7oYjKGg" x="912" y="159" width="100" height="49"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_SREsAXVIEeylMKf7oYjKGg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_SREsAnVIEeylMKf7oYjKGg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_SREsA3VIEeylMKf7oYjKGg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_SRFTEnVIEeylMKf7oYjKGg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SREsBHVIEeylMKf7oYjKGg" width="4005" height="278"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_zQB3fXCkEeyFLZsHFOyECQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_mcp14HClEeyFLZsHFOyECQ" type="4001" element="_mconwHClEeyFLZsHFOyECQ" source="_zQB3bHCkEeyFLZsHFOyECQ" target="_OsvBU3EQEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mcqc8HClEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mcqc8XClEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mcp14XClEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mcp14nClEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r7k8sHClEeyFLZsHFOyECQ" type="4001" element="_r7kVoHClEeyFLZsHFOyECQ" source="_OsvBU3EQEeyFLZsHFOyECQ" target="_PUSJgHEQEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r7ljwHClEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r7ljwXClEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r7k8sXClEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r7k8snClEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2sL_kHClEeyFLZsHFOyECQ" type="4001" element="_2sLYgHClEeyFLZsHFOyECQ" source="_PUSJgHEQEeyFLZsHFOyECQ" target="_3JSyUHClEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2sL_k3ClEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2sL_lHClEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2sL_kXClEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2sL_knClEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__j18wHClEeyFLZsHFOyECQ" type="4001" element="__jqWkHClEeyFLZsHFOyECQ" source="_3JSyUHClEeyFLZsHFOyECQ" target="_YUt5IHEZEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__j18w3ClEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__j18xHClEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__j18wXClEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__j18wnClEeyFLZsHFOyECQ" points="[-1, -20, -153, 84]$[-1, -91, -153, 13]$[150, -91, -2, 13]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AyI74HCmEeyFLZsHFOyECQ" id="(0.02,0.48)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KJOnEHCmEeyFLZsHFOyECQ" type="4001" element="_KJOAAHCmEeyFLZsHFOyECQ" source="_YUt5IHEZEeyFLZsHFOyECQ" target="_ZvTAwHEZEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KJPOIHCmEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KJPOIXCmEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KJOnEXCmEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KJOnEnCmEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_56y-sHCnEeyFLZsHFOyECQ" type="4001" element="_56xJgHCnEeyFLZsHFOyECQ" source="_ZvTAwHEZEeyFLZsHFOyECQ" target="_56omoHCnEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_56zlwHCnEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_56zlwXCnEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_56y-sXCnEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_56y-snCnEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_70hgcHCnEeyFLZsHFOyECQ" type="4001" element="_70UsIHCnEeyFLZsHFOyECQ" source="_3JSyUHClEeyFLZsHFOyECQ" target="_3ynkFHEREeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_70hgc3CnEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_70hgdHCnEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_70hgcXCnEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_70hgcnCnEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Hyvl8HCoEeyFLZsHFOyECQ" type="4001" element="_HynDEHCoEeyFLZsHFOyECQ" source="_3JSyUHClEeyFLZsHFOyECQ" target="_Qgp6MHEJEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Hyvl83CoEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HywNAHCoEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Hyvl8XCoEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Hyvl8nCoEeyFLZsHFOyECQ" points="[0, 22, -683, 103]$[0, 126, -683, 207]$[529, 126, -154, 207]$[529, -80, -154, 1]$[683, -80, 0, 1]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WvaB0HEREeyFLZsHFOyECQ" id="(0.3023255813953488,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8BGHYHCoEeyFLZsHFOyECQ" type="4001" element="_8BFgUHCoEeyFLZsHFOyECQ" source="_3ynkFHEREeyFLZsHFOyECQ" target="_8BAn0HCoEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8BGHY3CoEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8BGHZHCoEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8BGHYXCoEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8BGHYnCoEeyFLZsHFOyECQ" points="[63, -8, -54, 276]$[108, -8, -9, 276]$[108, -252, -9, 32]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Hwz20HCpEeyFLZsHFOyECQ" type="4001" element="_HwyosHCpEeyFLZsHFOyECQ" source="_8BAn0HCoEeyFLZsHFOyECQ" target="_IJljMHCpEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Hwz203CpEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Hwz21HCpEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Hwz20XCpEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Hwz20nCpEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zPzbcHCpEeyFLZsHFOyECQ" type="4001" element="_zPstwHCpEeyFLZsHFOyECQ" source="_IJljMHCpEeyFLZsHFOyECQ" target="_zPnOMHCpEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zPzbc3CpEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zPzbdHCpEeyFLZsHFOyECQ" x="-7" y="-11"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zPzbcXCpEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zPzbcnCpEeyFLZsHFOyECQ" points="[0, -21, -162, 27]$[0, -44, -162, 4]$[147, -44, -15, 4]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ulj1sHCwEeyFLZsHFOyECQ" type="4001" element="_uljOoHCwEeyFLZsHFOyECQ" source="_3KWDIHEREeyFLZsHFOyECQ" target="_tzxMYHCwEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ulkcwHCwEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ulkcwXCwEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ulj1sXCwEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ulj1snCwEeyFLZsHFOyECQ" points="[-53, 18, 1, -393]$[-53, 396, 1, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ullq4HCwEeyFLZsHFOyECQ" id="(1.0,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0LcgIHCwEeyFLZsHFOyECQ" type="4001" element="_0Lb5EHCwEeyFLZsHFOyECQ" source="_tzxMYHCwEeyFLZsHFOyECQ" target="__pO7AHEREeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0LcgI3CwEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0LcgJHCwEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0LcgIXCwEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0LcgInCwEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1fmPoHCwEeyFLZsHFOyECQ" type="4001" element="_1flokHCwEeyFLZsHFOyECQ" source="__pO7AHEREeyFLZsHFOyECQ" target="_1x6HoHCwEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1fmPo3CwEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1fmPpHCwEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1fmPoXCwEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1fmPonCwEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SbeToXCyEeyFLZsHFOyECQ" type="4001" element="_SbdskHCyEeyFLZsHFOyECQ" source="_1x6HoHCwEeyFLZsHFOyECQ" target="_SbXl8HCyEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sbe6sHCyEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sbe6sXCyEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SbeTonCyEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SbeTo3CyEeyFLZsHFOyECQ" points="[0, -21, -184, 65]$[0, -79, -184, 7]$[170, -79, -14, 7]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TjrR0HCyEeyFLZsHFOyECQ" type="4001" element="_TjmZUHCyEeyFLZsHFOyECQ" source="_1x6HoHCwEeyFLZsHFOyECQ" target="_T2A9YHESEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Tjr44HCyEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Tjr44XCyEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TjrR0XCyEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TjrR0nCyEeyFLZsHFOyECQ" points="[0, 22, -175, -68]$[0, 75, -175, -15]$[125, 75, -50, -15]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_90cIwHCyEeyFLZsHFOyECQ" type="4001" element="_90a6oHCyEeyFLZsHFOyECQ" source="_T2A9YHESEeyFLZsHFOyECQ" target="_V5uhkHESEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_90cIw3CyEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_90cIxHCyEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_90cIwXCyEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_90cIwnCyEeyFLZsHFOyECQ" points="[50, 0, -170, 333]$[203, 0, -17, 333]$[203, -308, -17, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EFvHsnCzEeyFLZsHFOyECQ" type="4001" element="_EFugoHCzEeyFLZsHFOyECQ" source="_V5uhkHESEeyFLZsHFOyECQ" target="_ESmfAHCzEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EFvuwHCzEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EFvuwXCzEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EFvHs3CzEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EFvHtHCzEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GWaw4HCzEeyFLZsHFOyECQ" type="4001" element="_GWaJ0HCzEeyFLZsHFOyECQ" source="_ESmfAHCzEeyFLZsHFOyECQ" target="_hCEVs3EXEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GWbX8HCzEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GWbX8XCzEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GWaw4XCzEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GWaw4nCzEeyFLZsHFOyECQ" points="[-1, -20, -134, 88]$[-1, -110, -134, -2]$[83, -110, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MRBuIXCzEeyFLZsHFOyECQ" type="4001" element="_MRBHEHCzEeyFLZsHFOyECQ" source="_hCEVs3EXEeyFLZsHFOyECQ" target="_hzfyoHEXEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MRCVMHCzEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MRCVMXCzEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MRBuInCzEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MRBuI3CzEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QGduoHCzEeyFLZsHFOyECQ" type="4001" element="_QGdHkHCzEeyFLZsHFOyECQ" source="_hzfyoHEXEeyFLZsHFOyECQ" target="_QSCFcHCzEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QGduo3CzEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QGdupHCzEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QGduoXCzEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QGduonCzEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RWof8HEJEeyFLZsHFOyECQ" type="4001" element="_RWjncHEJEeyFLZsHFOyECQ" source="_IJljMHCpEeyFLZsHFOyECQ" target="_Qgp6MHEJEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RWpHAHEJEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RWpHAXEJEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RWof8XEJEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RWof8nEJEeyFLZsHFOyECQ" points="[-22, 10, -233, -213]$[-22, 215, -233, -8]$[-7, 215, -218, -8]$[-7, 221, -218, -2]$[192, 221, -19, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RWqVIHEJEeyFLZsHFOyECQ" id="(1.0,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SdJcEHEJEeyFLZsHFOyECQ" type="4001" element="_SdIN8HEJEeyFLZsHFOyECQ" source="_Qgp6MHEJEeyFLZsHFOyECQ" target="_3KWDIHEREeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SdKDIHEJEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SdKDIXEJEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SdJcEXEJEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SdJcEnEJEeyFLZsHFOyECQ" points="[-16, 5, -4, -49]$[-13, 52, -1, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SdMfYHEJEeyFLZsHFOyECQ" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SdMfYXEJEeyFLZsHFOyECQ" id="(0.46,0.04)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VQWjgHEJEeyFLZsHFOyECQ" type="4001" element="_VQV8cHEJEeyFLZsHFOyECQ" source="_QSCFcHCzEeyFLZsHFOyECQ" target="_Qgp6MHEJEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VQXKkHEJEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VQXKkXEJEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VQWjgXEJEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VQWjgnEJEeyFLZsHFOyECQ" points="[-23, -29, 1130, -342]$[-23, -57, 1130, -370]$[-1147, -57, 6, -370]$[-1147, 314, 6, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VQYYsHEJEeyFLZsHFOyECQ" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VQYYsXEJEeyFLZsHFOyECQ" id="(0.5813953488372093,0.18604651162790697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eiuGwHEJEeyFLZsHFOyECQ" type="4001" element="_eimyAHEJEeyFLZsHFOyECQ" source="_QSCFcHCzEeyFLZsHFOyECQ" target="_eigrYHEJEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eiut0HEJEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eiut0XEJEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eiuGwXEJEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eiuGwnEJEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ykFjUHEJEeyFLZsHFOyECQ" type="4001" element="_ykAq0HEJEeyFLZsHFOyECQ" source="_ESmfAHCzEeyFLZsHFOyECQ" target="_y0pu4HEJEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ykGKYHEJEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ykGKYXEJEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ykFjUXEJEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ykFjUnEJEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_56XNUHEJEeyFLZsHFOyECQ" type="4001" element="_56NcUHEJEeyFLZsHFOyECQ" source="_QSCFcHCzEeyFLZsHFOyECQ" target="_y0pu4HEJEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_56X0YHEJEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_56X0YXEJEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_56XNUXEJEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_56XNUnEJEeyFLZsHFOyECQ" points="[-17, 7, 6, -272]$[-23, 281, 0, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_56a3sHEJEeyFLZsHFOyECQ" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_56a3sXEJEeyFLZsHFOyECQ" id="(0.37209302325581395,0.046511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_81ndgHEJEeyFLZsHFOyECQ" type="4001" element="_81m2cHEJEeyFLZsHFOyECQ" source="_y0pu4HEJEeyFLZsHFOyECQ" target="_WjYT2HEYEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_81ndg3EJEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_81ndhHEJEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_81ndgXEJEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_81ndgnEJEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SdBDwHEKEeyFLZsHFOyECQ" type="4001" element="_SdAcsHEKEeyFLZsHFOyECQ" source="_INX7wHEREeyFLZsHFOyECQ" target="_QeFxkHENEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SdBDw3EKEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SdBDxHEKEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SdBDwXEKEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SdBDwnEKEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_k7H90HEKEeyFLZsHFOyECQ" type="4001" element="_k7GvsHEKEeyFLZsHFOyECQ" source="_kDOFcHEKEeyFLZsHFOyECQ" target="_dTBkAHEKEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_k7H903EKEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_k7H91HEKEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_k7H90XEKEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_k7H90nEKEeyFLZsHFOyECQ" points="[-1, -16, -74, 0]$[64, -28, -9, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_k7JzAHEKEeyFLZsHFOyECQ" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lL0sQHEKEeyFLZsHFOyECQ" type="4001" element="_lLzeIHEKEeyFLZsHFOyECQ" source="_dTBkAHEKEeyFLZsHFOyECQ" target="_zQB3bHCkEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lL0sQ3EKEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lL0sRHEKEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lL0sQXEKEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lL0sQnEKEeyFLZsHFOyECQ" points="[-1, -5, -107, -4]$[46, -5, -60, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lL16YHEKEeyFLZsHFOyECQ" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oZ25EHELEeyFLZsHFOyECQ" type="4001" element="_oZ2SAHELEeyFLZsHFOyECQ" source="_8y0DUHEYEeyFLZsHFOyECQ" target="__pVkgXEYEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oZ25E3ELEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oZ3gIHELEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oZ25EXELEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oZ25EnELEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wFOM0HEMEeyFLZsHFOyECQ" type="4001" element="_wFNlwHEMEeyFLZsHFOyECQ" source="_QeFxkHENEeyFLZsHFOyECQ" target="_y1kXEHEYEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wFOM03EMEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wFOM1HEMEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wFOM0XEMEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wFOM0nEMEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0wS00HEMEeyFLZsHFOyECQ" type="4001" element="_0wSNwHEMEeyFLZsHFOyECQ" source="_y1kXEHEYEeyFLZsHFOyECQ" target="_BOJmM3EZEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0wTb4HEMEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0wTb4XEMEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0wS00XEMEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0wS00nEMEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7rjWwnEMEeyFLZsHFOyECQ" type="4001" element="_7rivsHEMEeyFLZsHFOyECQ" source="_BOJmM3EZEeyFLZsHFOyECQ" target="_-ke1QHEYEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7rj90HEMEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7rj90XEMEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7rjWw3EMEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7rjWxHEMEeyFLZsHFOyECQ" points="[7, -30, -156, 671]$[7, -365, -156, 336]$[133, -365, -30, 336]$[133, -672, -30, 29]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JGi8QHENEeyFLZsHFOyECQ" type="4001" element="_JGiVMHENEeyFLZsHFOyECQ" source="_-ke1QHEYEeyFLZsHFOyECQ" target="_jKoTwnEOEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JGi8Q3ENEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JGi8RHENEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JGi8QXENEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JGi8QnENEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QG1vMHENEeyFLZsHFOyECQ" type="4001" element="_QG0hEHENEeyFLZsHFOyECQ" source="_QeFxkHENEeyFLZsHFOyECQ" target="_Q1_7Q3ENEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QG2WQHENEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QG2WQXENEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QG1vMXENEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QG1vMnENEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SBIRoHENEeyFLZsHFOyECQ" id="(0.5116279069767442,0.9302325581395349)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_THVEsHENEeyFLZsHFOyECQ" type="4001" element="_THUdoHENEeyFLZsHFOyECQ" source="_jKoTwnEOEeyFLZsHFOyECQ" target="_Q1_7Q3ENEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_THVrwHENEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_THVrwXENEeyFLZsHFOyECQ" x="-87" y="14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_THVEsXENEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_THVEsnENEeyFLZsHFOyECQ" points="[-23, 7, 541, -176]$[-23, 183, 541, 0]$[-563, 183, 1, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_THYIAHENEeyFLZsHFOyECQ" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_THYIAXENEeyFLZsHFOyECQ" id="(0.9767441860465116,0.4883720930232558)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kmPyonENEeyFLZsHFOyECQ" type="4001" element="_kmPLkHENEeyFLZsHFOyECQ" source="_WjYT2HEYEeyFLZsHFOyECQ" target="_6sM1wHEQEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kmQZsHENEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kmQZsXENEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kmPyo3ENEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kmPypHENEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s2z6oHENEeyFLZsHFOyECQ" type="4001" element="_s2ysgHENEeyFLZsHFOyECQ" source="_Q1_7Q3ENEeyFLZsHFOyECQ" target="_8y0DUHEYEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s2z6o3ENEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s2z6pHENEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s2z6oXENEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s2z6onENEeyFLZsHFOyECQ" points="[-16, 7, -1, -69]$[-15, 73, 0, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s21v0HENEeyFLZsHFOyECQ" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s21v0XENEeyFLZsHFOyECQ" id="(0.3412698412698413,0.06349206349206349)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vMG-EXENEeyFLZsHFOyECQ" type="4001" element="_vMGXAHENEeyFLZsHFOyECQ" source="_6sM1wHEQEeyFLZsHFOyECQ" target="_INX7wHEREeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vMHlIHENEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vMHlIXENEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vMG-EnENEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vMG-E3ENEeyFLZsHFOyECQ" points="[-1, -9, -46, 0]$[37, -9, -8, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vMIzQHENEeyFLZsHFOyECQ" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vMIzQXENEeyFLZsHFOyECQ" id="(0.11,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vyaJEnENEeyFLZsHFOyECQ" type="4001" element="_vyZiAHENEeyFLZsHFOyECQ" source="_jKoTwnEOEeyFLZsHFOyECQ" target="_6sM1wHEQEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vyawIHENEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vyawIXENEeyFLZsHFOyECQ" x="-352" y="-20"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vyaJE3ENEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vyaJFHENEeyFLZsHFOyECQ" points="[-39, -19, 849, -14]$[-39, -116, 849, -111]$[-888, -116, 0, -111]$[-888, -26, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vyclUHENEeyFLZsHFOyECQ" id="(1.0,0.8372093023255814)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A2wa4HEOEeyFLZsHFOyECQ" type="4001" element="_A2vz0HEOEeyFLZsHFOyECQ" source="_jKoTwnEOEeyFLZsHFOyECQ" target="_A2qUQHEOEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A2xB8HEOEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A2xB8XEOEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A2wa4XEOEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A2wa4nEOEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_N_VasHEOEeyFLZsHFOyECQ" type="4001" element="_N_OF8HEOEeyFLZsHFOyECQ" source="_QeFxkHENEeyFLZsHFOyECQ" target="_GWbvonEOEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_N_WBwHEOEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_N_WBwXEOEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_N_VasXEOEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_N_VasnEOEeyFLZsHFOyECQ" points="[-1, -10, 15, 115]$[-15, -110, 1, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N_XP4HEOEeyFLZsHFOyECQ" id="(1.0,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RhItgHEOEeyFLZsHFOyECQ" type="4001" element="_RhIGcHEOEeyFLZsHFOyECQ" source="_GWbvonEOEeyFLZsHFOyECQ" target="_dTBkAHEKEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RhItg3EOEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RhIthHEOEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RhItgXEOEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RhItgnEOEeyFLZsHFOyECQ" points="[-22, -33, 2677, -81]$[-2696, -33, 3, -81]$[-2696, 40, 3, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RhJ7oHEOEeyFLZsHFOyECQ" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RhJ7oXEOEeyFLZsHFOyECQ" id="(0.3953488372093023,0.20930232558139536)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_X46u8nEOEeyFLZsHFOyECQ" type="4001" element="_X46H4HEOEeyFLZsHFOyECQ" source="_jKoTwnEOEeyFLZsHFOyECQ" target="_GWbvonEOEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_X47WAHEOEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_X47WAXEOEeyFLZsHFOyECQ" x="-110" y="-13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_X46u83EOEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_X46u9HEOEeyFLZsHFOyECQ" points="[-20, -33, 605, 128]$[-20, -156, 605, 5]$[-608, -156, 17, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_X48kIHEOEeyFLZsHFOyECQ" id="(1.0,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7tY34HEOEeyFLZsHFOyECQ" type="4001" element="_7tYQ0HEOEeyFLZsHFOyECQ" source="__pVkgXEYEeyFLZsHFOyECQ" target="_ARXN0HEZEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7tY343EOEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7tY35HEOEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7tY34XEOEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7tY34nEOEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OWikUHEPEeyFLZsHFOyECQ" type="4001" element="_OWh9QHEPEeyFLZsHFOyECQ" source="_ARXN0HEZEeyFLZsHFOyECQ" target="_L3fH8HEPEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OWikU3EPEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OWikVHEPEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OWikUXEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OWikUnEPEeyFLZsHFOyECQ" points="[0, -8, -68, 0]$[65, 3, -3, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OWkZgHEPEeyFLZsHFOyECQ" id="(1.0,0.68)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZewO4HEPEeyFLZsHFOyECQ" type="4001" element="_Zevn0HEPEeyFLZsHFOyECQ" source="_L3fH8HEPEeyFLZsHFOyECQ" target="_E5vHI3EZEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZewO43EPEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZewO5HEPEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZewO4XEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZewO4nEPEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ae-VwHEPEeyFLZsHFOyECQ" type="4001" element="_ae9usHEPEeyFLZsHFOyECQ" source="_E5vHI3EZEeyFLZsHFOyECQ" target="_ae5dQnEPEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ae-Vw3EPEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ae-VxHEPEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ae-VwXEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ae-VwnEPEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cO-TwHEPEeyFLZsHFOyECQ" type="4001" element="_cO9ssHEPEeyFLZsHFOyECQ" source="_ae5dQnEPEeyFLZsHFOyECQ" target="_UNrLQXEZEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cO-Tw3EPEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cO-60HEPEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cO-TwXEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cO-TwnEPEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kIRLQHEPEeyFLZsHFOyECQ" type="4001" element="_kIQkMHEPEeyFLZsHFOyECQ" source="_ae5dQnEPEeyFLZsHFOyECQ" target="_VcJwkHEZEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kIRLQ3EPEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kIRLRHEPEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kIRLQXEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kIRLQnEPEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qn6IMHEPEeyFLZsHFOyECQ" type="4001" element="_qn5hIHEPEeyFLZsHFOyECQ" source="_VcJwkHEZEeyFLZsHFOyECQ" target="_qFwdYHEPEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qn6IM3EPEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qn6INHEPEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qn6IMXEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qn6IMnEPEeyFLZsHFOyECQ" points="[0, -5, -64, 1]$[65, -2, 1, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qn7WUHEPEeyFLZsHFOyECQ" id="(1.0,0.64)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qn79YHEPEeyFLZsHFOyECQ" id="(0.09302325581395349,0.46511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ryhhMHEPEeyFLZsHFOyECQ" type="4001" element="_ryg6IHEPEeyFLZsHFOyECQ" source="_UNrLQXEZEeyFLZsHFOyECQ" target="_qFwdYHEPEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ryhhM3EPEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ryhhNHEPEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ryhhMXEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ryhhMnEPEeyFLZsHFOyECQ" points="[0, 0, -133, -589]$[132, 574, -1, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ryjWYHEPEeyFLZsHFOyECQ" id="(1.0,0.4375)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tHtLcHEPEeyFLZsHFOyECQ" type="4001" element="_tHskYHEPEeyFLZsHFOyECQ" source="_qFwdYHEPEeyFLZsHFOyECQ" target="_tHnr4HEPEeyFLZsHFOyECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tHtygHEPEeyFLZsHFOyECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tHtygXEPEeyFLZsHFOyECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tHtLcXEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tHtLcnEPEeyFLZsHFOyECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1Aj-EHEPEeyFLZsHFOyECQ" type="4003" element="_1Aiv8HEPEeyFLZsHFOyECQ" source="_yeKSwHEPEeyFLZsHFOyECQ" target="_dTBkAHEKEeyFLZsHFOyECQ">
      <styles xmi:type="notation:FontStyle" xmi:id="_1Aj-EXEPEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1Aj-EnEPEeyFLZsHFOyECQ" points="[-10, -8, 43, 45]$[-57, -42, -4, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1AnocHEPEeyFLZsHFOyECQ" id="(1.0,0.22)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1YwJsHEREeyFLZsHFOyECQ" type="4003" element="_1YvioHEREeyFLZsHFOyECQ" source="_uLqQ4HEREeyFLZsHFOyECQ" target="_Qgp6MHEJEeyFLZsHFOyECQ">
      <styles xmi:type="notation:FontStyle" xmi:id="_1YwJsXEREeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1YwJsnEREeyFLZsHFOyECQ" points="[-98, 1, 81, 1]$[-178, 16, 1, 16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1Yx-4HEREeyFLZsHFOyECQ" id="(1.0,0.11956521739130435)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gfmsYHEYEeyFLZsHFOyECQ" type="4003" element="_gfmFUHEYEeyFLZsHFOyECQ" source="_ZkbC8HEYEeyFLZsHFOyECQ" target="_6sM1wHEQEeyFLZsHFOyECQ">
      <styles xmi:type="notation:FontStyle" xmi:id="_gfmsYXEYEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gfmsYnEYEeyFLZsHFOyECQ" points="[0, 0, -24, 29]$[24, -33, 0, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gfn6gHEYEeyFLZsHFOyECQ" id="(1.0,0.125)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gfn6gXEYEeyFLZsHFOyECQ" id="(0.23255813953488372,0.3953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wb370HEYEeyFLZsHFOyECQ" type="4003" element="_wb3UwHEYEeyFLZsHFOyECQ" source="_oDnQYXEYEeyFLZsHFOyECQ" target="_GWbvonEOEeyFLZsHFOyECQ">
      <styles xmi:type="notation:FontStyle" xmi:id="_wb370XEYEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wb370nEYEeyFLZsHFOyECQ" points="[0, 1, -44, 0]$[40, 12, -4, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wb5J8HEYEeyFLZsHFOyECQ" id="(1.0,0.24)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5s0iwHEYEeyFLZsHFOyECQ" type="4003" element="_5sz7sHEYEeyFLZsHFOyECQ" source="_0teT4HEYEeyFLZsHFOyECQ" target="_Q1_7Q3ENEeyFLZsHFOyECQ">
      <styles xmi:type="notation:FontStyle" xmi:id="_5s0iwXEYEeyFLZsHFOyECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5s0iwnEYEeyFLZsHFOyECQ" points="[0, 4, -49, -3]$[47, -6, -2, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5s1w4HEYEeyFLZsHFOyECQ" id="(1.0,0.06976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kkn74HVIEeylMKf7oYjKGg" type="4001" element="_kkmtwHVIEeylMKf7oYjKGg" source="_jv_Z8HVIEeylMKf7oYjKGg" target="_n6r4wHVIEeylMKf7oYjKGg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kkoi8HVIEeylMKf7oYjKGg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kkoi8XVIEeylMKf7oYjKGg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kkn74XVIEeylMKf7oYjKGg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kkn74nVIEeylMKf7oYjKGg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qkqywHVIEeylMKf7oYjKGg" type="4001" element="_qkqLsHVIEeylMKf7oYjKGg" source="_sLowkHVIEeylMKf7oYjKGg" target="_uVHlkXVIEeylMKf7oYjKGg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qkrZ0HVIEeylMKf7oYjKGg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qkrZ0XVIEeylMKf7oYjKGg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qkqywXVIEeylMKf7oYjKGg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qkqywnVIEeylMKf7oYjKGg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BSIpMHVJEeylMKf7oYjKGg" type="4001" element="_BSICIHVJEeylMKf7oYjKGg" source="_uVHlkXVIEeylMKf7oYjKGg" target="_Bq68oHVJEeylMKf7oYjKGg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BSIpM3VJEeylMKf7oYjKGg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BSIpNHVJEeylMKf7oYjKGg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BSIpMXVJEeylMKf7oYjKGg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BSIpMnVJEeylMKf7oYjKGg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CVC3sHVJEeylMKf7oYjKGg" type="4001" element="_CVCQoHVJEeylMKf7oYjKGg" source="_Bq68oHVJEeylMKf7oYjKGg" target="_XQhzIHVJEeylMKf7oYjKGg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CVDewHVJEeylMKf7oYjKGg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CVDewXVJEeylMKf7oYjKGg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CVC3sXVJEeylMKf7oYjKGg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CVC3snVJEeylMKf7oYjKGg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PxeAkHVJEeylMKf7oYjKGg" type="4001" element="_PxdZgHVJEeylMKf7oYjKGg" source="_n6r4wHVIEeylMKf7oYjKGg" target="_P_HbAHVJEeylMKf7oYjKGg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PxenoHVJEeylMKf7oYjKGg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PxenoXVJEeylMKf7oYjKGg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PxeAkXVJEeylMKf7oYjKGg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PxeAknVJEeylMKf7oYjKGg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QKVzkHVJEeylMKf7oYjKGg" type="4001" element="_QKUlcHVJEeylMKf7oYjKGg" source="_P_HbAHVJEeylMKf7oYjKGg" target="_sLowkHVIEeylMKf7oYjKGg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QKVzk3VJEeylMKf7oYjKGg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QKWaoHVJEeylMKf7oYjKGg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QKVzkXVJEeylMKf7oYjKGg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QKVzknVJEeylMKf7oYjKGg" points="[-3, -6, -52, 1]$[49, 12, 0, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QKYP0HVJEeylMKf7oYjKGg" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QKYP0XVJEeylMKf7oYjKGg" id="(0.13,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QoPQgHVJEeylMKf7oYjKGg" type="4001" element="_QoJw8HVJEeylMKf7oYjKGg" source="_Bq68oHVJEeylMKf7oYjKGg" target="_P_HbAHVJEeylMKf7oYjKGg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QoP3kHVJEeylMKf7oYjKGg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QoP3kXVJEeylMKf7oYjKGg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QoPQgXVJEeylMKf7oYjKGg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QoPQgnVJEeylMKf7oYjKGg" points="[-22, -34, 416, -19]$[-22, -83, 416, -68]$[-438, -83, 0, -68]$[-438, -36, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QoRFsHVJEeylMKf7oYjKGg" id="(1.0,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WkInMHVJEeylMKf7oYjKGg" type="4001" element="_WkIAIHVJEeylMKf7oYjKGg" source="_XQhzIHVJEeylMKf7oYjKGg" target="_WkDHoHVJEeylMKf7oYjKGg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WkJOQHVJEeylMKf7oYjKGg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WkJOQXVJEeylMKf7oYjKGg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WkInMXVJEeylMKf7oYjKGg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WkInMnVJEeylMKf7oYjKGg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
